name: Continuous Integration
on:
  push:
    branches:
      - main # ou qualquer outra branch
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Simulando Continuous Delivery
      - uses: actions/upload-artifact@v7
        with:
          name: projetozipado.zip
          path: |
            main.py
            README.MD
            